# Site Params

# Open Graph, Twitter Cards and schema.org Thing and Article (in posts)
# https://gohugo.io/templates/internal/#open-graph
# https://gohugo.io/templates/internal/#twitter-cards
# https://schema.org/Thing
# https://schema.org/Article
description = "Hugo theme for a secure, blazing fast and SEO-ready static website, using Bootstrap 5."
images = ['images/logo.svg','images/site-feature-image.png']
mainMenuLogo = "images/logo.svg"

[outputs]
  home = ["HTML", "RSS", "JSON"]

comments = [
    {repo = "mansoorbarri/website", theme = "github-light", title = "title"}
]

  placeholder = [
      {views = "5", likes = "4"}
  ]

    favicon = "/img/favicon.png"
    headerLogo = "/img/logo1.webp"
    headerImage = "/img/main.webp"
    paginate = 4
    aboutImageR = "/img/main/about.webp"
    aboutImageL = "/img/main/tools.webp"
    subscriptionText = "SUBSCRIBE VIA EMAIL"
    subscriptionBtnText = "Subscribe Now"
    subscriptionPlaceholder = "Email Address"
    copyrightText = "All rights reserved."
    email = "marcel@marcelvenema.com"
    mainSections = ["blogs"]





# For favicons
## Chrome Browser
themeColor = "#fff"

# Alert
alert = false
alertDismissable = false
alertText = "Introducing this new service! <a class=\"alert-link stretched-link\" href=\"https://salvus.site/\">Check out Total Security</a>"

# Pre-footer
footerAbout = true
footerAboutTitle = "Few Words About Us"
footerAboutText = "We protect your website so you can provide a safe environment to build trust and improve the user experience of your visitors.<br/><br/>Salvus Site is the partner that you can rely on for preventive and reactive cybersecurity."

[options]
  bootStrapJs = true
  breadCrumb = true
  listCategoryFilter = true
  listTagFilter = true
