[en]
  languageName = "English"
  languageCode = "en-US"
  weight = 10
  [en.params]
    languageISO = "EN"

[pt]
  languageName = "Nederlands"
  languageCode = "nl-NL"
  weight = 20
  [pt.params]
    languageISO = "NL"
