baseURL = 'https://marcelvenema.github.io/'
languageCode = 'en-us'
title = 'MarcelVenema'
theme = "m10c"
paginate = 20


[params]
  author = "Marcel Venema"
  description = "A blog about all things technical."

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/MarcelVenema"


[menus]

[[menu.main]]
  identifier = "home"
  name = "Home"
  pageRef = "/"
  weight = 10

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  pageRef = "/blog"
  weight = 20

[[menu.main]]
  identifier = "training"
  name = "Training"
  pageRef = "/training"
  weight = 30

[[menu.main]]
  identifier = "tools"
  name = "Tools"
  pageRef = "/tools"
    weight = 40

[[menu.main]]
  identifier = "about"
  name = "About"
  pageRef = "/about"
  weight = 50
