baseURL = 'https://marcelvenema.github.io/'
languageCode = 'en-us'
title = 'MarcelVenema'
theme = "m10c"

[params]
  author = "Marcel Venema"
  description = "A blog about all things technical."

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/MarcelVenema"


[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"