baseURL = 'https://marcelvenema.com/'
languageCode = 'en-us'
title = 'MarcelVenema.com'
theme = 'hugo-canvas'


[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'BLOG'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'TOOLS'
pageRef = '/tools'
weight = 60


[[menus.main]]
name = 'ABOUT'
pageRef = '/about'
weight = 60

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"