[[main]]
name = "HOME"
url = "/"
weight = 10

[[main]]
identifier = "blogs"
name = "BLOG"
url = "/blogs"
weight = 20

[[main]]
identifier = "training"
name = "TRAINING"
url = "/training"
weight = 30

[[main]]
identifier = "tools"
name = "TOOLS"
url = "/page"
weight = 40

[[main]]
name = "ABOUT"
url = "/about"
weight = 50
# title = "Made with ❤️ by the Hugo Bootstrap Theme team"


[[social]]
  name = "GitHub"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-github'><use href='/images/feather/feather-sprite.svg#github'/></svg>"
  url = "https://github.com/marcelvenema/"
  weight = 10
  title = "Visit my GitHub repository"

[[social]]
  name = "Twitter"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-twitter'><use href='/images/feather/feather-sprite.svg#twitter'/></svg>"
  url = "https://twitter.com/marcel_venema/"
  weight = 20
  title = "View my tweets"

[[social]]
  name = "LinkedIn"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-twitter'><use href='/images/feather/feather-sprite.svg#linkedin'/></svg>"
  url = "https://linkedin.com/in/marcelvenema/"
  weight = 30
  title = "Visit my LinkedIn Profile"